# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Ziqi-Yang"

[social.params]
icon = "brand-github"

[[social]]
identifier = "archlinux"
name = "AUR"
url = "https://aur.archlinux.org/packages?K=Zarkli&SeB=m"

[social.params]
icon = "archlinux"

[[social]]
identifier = "rss"
name = "Rss"
url = "posts/index.xml"

[social.params]
icon = "rss"
